
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione_5;

/** CUP generated interface containing symbol constants. */
public interface YASPL3Sym {
  /* terminals */
  public static final int CHAR_CONST = 51;
  public static final int LGPAR = 31;
  public static final int CHAR = 8;
  public static final int GE = 38;
  public static final int TWOPOINTS = 22;
  public static final int LQPAR = 25;
  public static final int UMINUS = 56;
  public static final int DOUBLE_CONST = 50;
  public static final int CASE = 21;
  public static final int DOUBLE = 6;
  public static final int SEMI = 27;
  public static final int INT = 4;
  public static final int OUT = 47;
  public static final int FOR = 17;
  public static final int MINUS = 34;
  public static final int WRITE = 54;
  public static final int INOUT = 48;
  public static final int AND = 43;
  public static final int NOT = 42;
  public static final int LT = 39;
  public static final int RPAR = 30;
  public static final int IN = 46;
  public static final int OR = 44;
  public static final int BOOL = 5;
  public static final int RGPAR = 32;
  public static final int COMMA = 28;
  public static final int DIV = 36;
  public static final int PLUS = 33;
  public static final int ASSIGN = 45;
  public static final int IF = 12;
  public static final int ID = 55;
  public static final int LE = 40;
  public static final int RQPAR = 26;
  public static final int EOF = 0;
  public static final int INT_CONST = 49;
  public static final int TRUE = 10;
  public static final int error = 1;
  public static final int MOD = 18;
  public static final int START = 3;
  public static final int BREAK = 23;
  public static final int EQ = 41;
  public static final int HEAD = 2;
  public static final int SWITCH = 20;
  public static final int TIMES = 35;
  public static final int ELSE = 16;
  public static final int READ = 53;
  public static final int WHILE = 14;
  public static final int DEFAULT = 24;
  public static final int THEN = 13;
  public static final int LPAR = 29;
  public static final int STRING = 7;
  public static final int DEF = 9;
  public static final int FALSE = 11;
  public static final int STRING_CONST = 52;
  public static final int STRUCT = 19;
  public static final int GT = 37;
  public static final int DO = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HEAD",
  "START",
  "INT",
  "BOOL",
  "DOUBLE",
  "STRING",
  "CHAR",
  "DEF",
  "TRUE",
  "FALSE",
  "IF",
  "THEN",
  "WHILE",
  "DO",
  "ELSE",
  "FOR",
  "MOD",
  "STRUCT",
  "SWITCH",
  "CASE",
  "TWOPOINTS",
  "BREAK",
  "DEFAULT",
  "LQPAR",
  "RQPAR",
  "SEMI",
  "COMMA",
  "LPAR",
  "RPAR",
  "LGPAR",
  "RGPAR",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NOT",
  "AND",
  "OR",
  "ASSIGN",
  "IN",
  "OUT",
  "INOUT",
  "INT_CONST",
  "DOUBLE_CONST",
  "CHAR_CONST",
  "STRING_CONST",
  "READ",
  "WRITE",
  "ID",
  "UMINUS"
  };
}

